#!/bin/ksh

echo -ne "Enter IOR: "
read ior

echo -ne "Enter k: "
read k

top=$(( pow(ior-1,2) + pow(k,2) ))
bottom=$(( pow(ior+1,2) + pow(k,2) ))

echo $top
echo $bottom

result=$(( top / bottom ))
echo "Normalized reflectance at normal: " $result

